### PR TITLE
Adding parser functionality

### PR DESCRIPTION
**Pull request by ncrubin**
There are two large changes.

1) python parser front end and code generation is added to pdaggerq. This
allows a user to generate CC codes.  Worked examples for code generation modules
interfacing with the C++ pdaggerq module are provided in examples.  In
examples/full_cc_codes we provide a pedagogical example of CCSD and lambda-CCSD
codes.

2) The module generated by pybind is now called _pdaggerq.  The reason for the
change is that inorder to have a python module named pdaggerq that contained
the C++ module code and the python parsing code we need to change the name
of the C++ module.  Following python conventions we made the module generated
by pybind _pdaggerq and import ._pdaggerq * in the __init__.py of the
pdaggerq module containing the python code.

### CODE REVIEW

**Comment by edeprince3** [comment]
For the T2 example, you need to have the \*'s on the same labels in E and F, so i* j* k n* m l + n* m l i* j* k is what you want

**Comment by ncrubin** [comment]
oof...how embarrassing.

**Comment by ncrubin** [comment]
@edeprince3 added T2 and T1 correctly consistent with J. Chem. Theory Comput. 2017, 13, 9, 4113–4122.  Also quickly tried to roll my own eRPA expressions as a function of 2-RDM.

**Comment by edeprince3** [comment]
> oof...how embarrassing.

at least you didn't publish exactly that mistake in 2016

**Pull request merged**
